"""Track Record — review the accuracy of past price projections generated by the app."""
from __future__ import annotations

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

from modules.prediction_tracker import get_all_predictions, get_summary_stats, resolve_pending_predictions

st.title("📈 Track Record")
st.caption(
    "Automatically verifies whether past price projections hit their targets once the "
    "estimated date has passed. Uses split-adjusted historical prices."
)

# ---------------------------------------------------------------------------
# Trigger resolution on page load (cheap — only processes overdue predictions).
# ---------------------------------------------------------------------------
with st.spinner("Checking for predictions ready to resolve…"):
    try:
        resolution_summary = resolve_pending_predictions()
        newly_resolved = resolution_summary.get("resolved", 0)
        if newly_resolved:
            st.success(f"✅ Resolved {newly_resolved} prediction(s) since your last visit.")
    except Exception as exc:
        st.warning(f"Could not run resolution check: {exc}")

# ---------------------------------------------------------------------------
# Load data
# ---------------------------------------------------------------------------
all_records = get_all_predictions()
stats = get_summary_stats()

resolved_records = [r for r in all_records if r.get("status") == "resolved"]
pending_records = [r for r in all_records if r.get("status") == "pending"]

# ---------------------------------------------------------------------------
# Summary metrics
# ---------------------------------------------------------------------------
if not all_records:
    st.info(
        "No predictions recorded yet. Run a **Profit Opportunities** scan or open the "
        "**Stock Analysis** page to start building a track record."
    )
    st.stop()

col1, col2, col3, col4, col5 = st.columns(5)
col1.metric("Total Predictions", stats["total_predictions"])
col2.metric("Resolved", stats["total_resolved"])
col3.metric("Pending", stats["total_pending"])

if stats["overall_hit_rate_target"] is not None:
    col4.metric("Hit Rate (strict)", f"{stats['overall_hit_rate_target']}%")
    col5.metric("Hit Rate (within band)", f"{stats['overall_hit_rate_band']}%")
else:
    col4.metric("Hit Rate (strict)", "—")
    col5.metric("Hit Rate (within band)", "—")

if stats["total_resolved"] == 0:
    st.info(
        f"**{stats['total_pending']}** prediction(s) are pending — check back after their target dates pass."
    )
    st.stop()

# ---------------------------------------------------------------------------
# Mean / Median Error
# ---------------------------------------------------------------------------
st.subheader("Forecast Error")
e1, e2 = st.columns(2)
e1.metric(
    "Mean Absolute % Error",
    f"{stats['mean_absolute_error_pct']:.2f}%" if stats["mean_absolute_error_pct"] is not None else "—",
)
e2.metric(
    "Median Absolute % Error",
    f"{stats['median_absolute_error_pct']:.2f}%" if stats["median_absolute_error_pct"] is not None else "—",
)

# ---------------------------------------------------------------------------
# Breakdown by horizon
# ---------------------------------------------------------------------------
st.subheader("Hit Rate by Horizon")
horizon_labels = {"short_term": "Short-Term", "medium_term": "Medium-Term", "long_term": "Long-Term"}
horizon_rows = []
for h, s in stats.get("by_horizon", {}).items():
    if s["count"] > 0:
        horizon_rows.append(
            {
                "Horizon": horizon_labels.get(h, h),
                "Count": s["count"],
                "Hit Rate (strict) %": s["hit_rate_target"],
                "Hit Rate (band) %": s["hit_rate_band"],
                "MAE %": s["mae_pct"],
            }
        )
if horizon_rows:
    st.dataframe(pd.DataFrame(horizon_rows).set_index("Horizon"), use_container_width=True)

# ---------------------------------------------------------------------------
# Breakdown by source
# ---------------------------------------------------------------------------
st.subheader("Hit Rate by Source")
source_rows = []
for src, s in stats.get("by_source", {}).items():
    if s["count"] > 0:
        source_rows.append(
            {
                "Source": src,
                "Count": s["count"],
                "Hit Rate (strict) %": s["hit_rate_target"],
                "Hit Rate (band) %": s["hit_rate_band"],
                "MAE %": s["mae_pct"],
            }
        )
if source_rows:
    st.dataframe(pd.DataFrame(source_rows).set_index("Source"), use_container_width=True)

# ---------------------------------------------------------------------------
# Calibration: by confidence tier
# ---------------------------------------------------------------------------
st.subheader("Calibration by Confidence Tier")
st.caption(
    "A well-calibrated model should show higher hit rates for 'High' confidence predictions "
    "than for 'Low' confidence ones."
)
conf_rows = []
for conf, s in stats.get("by_confidence", {}).items():
    if s["count"] > 0:
        conf_rows.append(
            {
                "Confidence": conf,
                "Count": s["count"],
                "Hit Rate (strict) %": s["hit_rate_target"],
                "Hit Rate (band) %": s["hit_rate_band"],
                "MAE %": s["mae_pct"],
            }
        )
if conf_rows:
    conf_df = pd.DataFrame(conf_rows).set_index("Confidence")
    st.dataframe(conf_df, use_container_width=True)

    # Calibration bar chart
    _CONF_COLORS = {
        "High": "#2ca02c",
        "Medium": "#ffbf00",
        "Low": "#ff8c00",
        "Limited": "#d62728",
    }
    fig_cal = go.Figure()
    for _conf in conf_df.index:
        _color = _CONF_COLORS.get(str(_conf), "#1f77b4")
        _val = conf_df.loc[_conf, "Hit Rate (strict) %"]
        fig_cal.add_bar(x=[_conf], y=[_val], name=str(_conf), marker_color=_color)
    fig_cal.update_layout(title="Hit Rate by Confidence Tier", yaxis_title="Hit Rate %", xaxis_title="Confidence")
    st.plotly_chart(fig_cal, use_container_width=True)

# ---------------------------------------------------------------------------
# Resolved predictions table
# ---------------------------------------------------------------------------
st.subheader("Resolved Predictions")

if not resolved_records:
    st.info("No resolved predictions yet.")
else:
    df_resolved = pd.DataFrame(resolved_records)

    # Filters
    with st.expander("🔍 Filters", expanded=False):
        f1, f2, f3 = st.columns(3)
        sel_horizons = f1.multiselect(
            "Horizon",
            options=["short_term", "medium_term", "long_term"],
            default=["short_term", "medium_term", "long_term"],
            format_func=lambda x: horizon_labels.get(x, x),
        )
        sel_sources = f2.multiselect(
            "Source",
            options=sorted(df_resolved["source"].unique().tolist()),
            default=sorted(df_resolved["source"].unique().tolist()),
        )
        sel_hit = f3.selectbox("Result", ["All", "Hit (strict)", "Miss (strict)", "Hit (band)"])

    mask = (df_resolved["horizon"].isin(sel_horizons)) & (df_resolved["source"].isin(sel_sources))
    if sel_hit == "Hit (strict)":
        mask &= df_resolved["hit_target"] == True  # noqa: E712
    elif sel_hit == "Miss (strict)":
        mask &= df_resolved["hit_target"] == False  # noqa: E712
    elif sel_hit == "Hit (band)":
        mask &= df_resolved["hit_band"] == True  # noqa: E712

    display_df = df_resolved[mask].copy()
    display_df["Horizon"] = display_df["horizon"].map(horizon_labels)
    display_df["Hit"] = display_df["hit_target"].map({True: "✅ Yes", False: "❌ No"})

    columns_to_show = [
        "ticker", "company", "Horizon", "scan_date", "target_date",
        "current_price_at_scan", "target_price", "actual_price_at_target_date",
        "projected_upside_pct", "actual_return_pct", "Hit", "data_quality", "source",
    ]
    columns_to_show = [c for c in columns_to_show if c in display_df.columns]
    display_df = display_df[columns_to_show].rename(
        columns={
            "ticker": "Ticker",
            "company": "Company",
            "scan_date": "Scan Date",
            "target_date": "Target Date",
            "current_price_at_scan": "Price at Scan",
            "target_price": "Target Price",
            "actual_price_at_target_date": "Actual Price",
            "projected_upside_pct": "Projected Upside %",
            "actual_return_pct": "Actual Return %",
            "data_quality": "Confidence",
            "source": "Source",
        }
    ).sort_values("Scan Date", ascending=False)

    st.dataframe(
        display_df.style.format(
            {
                "Price at Scan": "${:,.2f}",
                "Target Price": "${:,.2f}",
                "Actual Price": "${:,.2f}",
                "Projected Upside %": "{:.2f}%",
                "Actual Return %": "{:.2f}%",
            },
            na_rep="—",
        ),
        use_container_width=True,
    )

    st.download_button(
        "Export to CSV",
        display_df.to_csv(index=False),
        file_name="track_record.csv",
        mime="text/csv",
    )

    # Projected vs actual scatter
    scatter_df = display_df.dropna(subset=["Projected Upside %", "Actual Return %"])
    if not scatter_df.empty:
        fig_scatter = px.scatter(
            scatter_df,
            x="Projected Upside %",
            y="Actual Return %",
            color="Confidence",
            hover_data=["Ticker", "Horizon", "Scan Date"],
            title="Projected vs Actual Return",
            color_discrete_map={"High": "#2ca02c", "Medium": "#ffbf00", "Low": "#ff8c00", "Limited": "#d62728"},
        )
        fig_scatter.add_shape(
            type="line",
            x0=scatter_df["Projected Upside %"].min(),
            y0=scatter_df["Projected Upside %"].min(),
            x1=scatter_df["Projected Upside %"].max(),
            y1=scatter_df["Projected Upside %"].max(),
            line=dict(dash="dash", color="gray"),
        )
        st.plotly_chart(fig_scatter, use_container_width=True)

# ---------------------------------------------------------------------------
# Pending predictions
# ---------------------------------------------------------------------------
if pending_records:
    with st.expander(f"⏳ {len(pending_records)} Pending Prediction(s)", expanded=False):
        df_pending = pd.DataFrame(pending_records)[
            ["ticker", "company", "horizon", "scan_date", "target_date", "target_price", "projected_upside_pct", "data_quality", "source"]
        ].rename(
            columns={
                "ticker": "Ticker",
                "company": "Company",
                "horizon": "Horizon",
                "scan_date": "Scan Date",
                "target_date": "Target Date",
                "target_price": "Target Price",
                "projected_upside_pct": "Projected Upside %",
                "data_quality": "Confidence",
                "source": "Source",
            }
        )
        df_pending["Horizon"] = df_pending["Horizon"].map(horizon_labels)
        st.dataframe(df_pending.sort_values("Target Date"), use_container_width=True)

st.caption(
    "⚠️ Past accuracy does not guarantee future performance. "
    "Predictions use split-adjusted historical prices for resolution."
)
